Make 11-manage_my_process Wed Oct 16 17:40:52 SAST 2024 executable

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -13,14 +13,18 @@ case $1 in
         echo "manage_my_process started";;
     stop)
         if [[ -f '/var/run/my_process.pid' ]]; then
-            kill "$(tr '\n' ' ' < /var/run/my_process.pid)"
+            echo "Process not running"
+            exit 1
         fi
+        kill "$(tr '\n' ' ' < /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         echo "manage_my_process stopped";;
     restart)
         if [[ -f '/var/run/my_process.pid' ]]; then
-            kill "$(tr '\n' ' ' < /var/run/my_process.pid)"
+            echo "Process not running"
+            exit 1
         fi
+        kill "$(tr '\n' ' ' < /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         ./manage_my_process &
         echo "$!" >> /var/run/my_process.pid
