Make 11-manage_my_process Wed Oct 16 17:42:47 SAST 2024 executable

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -9,14 +9,14 @@ fi
 case $1 in
     start)
         ./manage_my_process &
-        echo "$!" >> /var/run/my_process.pid
+        echo "$!" > /var/run/my_process.pid
         echo "manage_my_process started";;
     stop)
         if [[ -f '/var/run/my_process.pid' ]]; then
             echo "Process not running"
             exit 1
         fi
-        kill "$(tr '\n' ' ' < /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
+        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         echo "manage_my_process stopped";;
     restart)
@@ -24,10 +24,10 @@ case $1 in
             echo "Process not running"
             exit 1
         fi
-        kill "$(tr '\n' ' ' < /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
+        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         ./manage_my_process &
-        echo "$!" >> /var/run/my_process.pid
+        echo "$!" > /var/run/my_process.pid
         echo "manage_my_process restarted";;
     *)
         echo "Usage: manage_my_process {start|stop|restart}";;
