Make 11-manage_my_process Wed Oct 16 17:46:34 SAST 2024 executable

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -12,19 +12,15 @@ case $1 in
         echo "$!" > /var/run/my_process.pid
         echo "manage_my_process started";;
     stop)
-        if [[ ! -f '/var/run/my_process.pid' ]]; then
-            echo "Process not running"
-            exit 1
+        if [[ -f '/var/run/my_process.pid' ]]; then
+            kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         fi
-        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         echo "manage_my_process stopped";;
     restart)
-        if [[ ! -f '/var/run/my_process.pid' ]]; then
-            echo "Process not running"
-            exit 1
+        if [[ -f '/var/run/my_process.pid' ]]; then
+            kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         fi
-        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
         rm /var/run/my_process.pid
         ./manage_my_process &
         echo "$!" > /var/run/my_process.pid
